### PR TITLE
Lookup assignments, even when store_unqualified is set to false

### PR DESCRIPTION
**Pull request by eljojo**
Verdict has the option `store_unqualified`, here's the behaviour it changes:

| store_unqualified                                                           | true | false |
|-----------------------------------------------------------------------------|------|-------|
| assignments for subjects that don't qualify are persisted in the database                   | yes  | no    |
| existing assignments are returned (even if subject doesn't qualify anymore) | yes  | no    |

With this PR, I want the following behaviour:

| store_unqualified                                                           | true | false |
|-----------------------------------------------------------------------------|------|-------|
| assignments for subjects that don't qualify are persisted in the database                   | yes  | no    |
| existing assignments are returned (even if subject doesn't qualify anymore) | yes  | **yes** |

Currently, for experiment definitions that have `store_unqualified: false`, we are [always](https://github.com/Shopify/verdict/blob/7c07bc12805506c5fa3a9f112be4240e933e4a86/lib/verdict/experiment.rb#L232) checking if the subject qualifies, even if it's already assigned to an experiment.

This is counterintuitive when compared with the behaviour of experiments that have `store_unqualified: true`, as it always [returns existing assignments](https://github.com/Shopify/verdict/blob/7c07bc12805506c5fa3a9f112be4240e933e4a86/lib/verdict/experiment.rb#L221-L222), even if they don't qualify anymore.

@wvanbergen I remember you had thoughts about removing this option completely. What is the behaviour that you'd like?

I'll fix the tests once we agree on something :)

### CODE REVIEW

**Comment by wvanbergen** [comment]
I contemplated whether we should simply always operate with `store_unqualified: false`. If it works for checkout experiments, why wouldn't it work for other experiments?

**Comment by eljojo** [comment]
I think that for the admin is a bit trickier, as we don't necessarily want
to show an experimental version of a feature to merchants if they've
already seen the non-experimental one (because they didn't qualify in the
past but they do now).

I think it makes sense to keep store_unqualified as true for
ShopExperiments.

**Comment by eljojo** [comment]
@wvanbergen thanks for following up on this.
We currently solved this using a custom experiment type, here: https://github.com/Shopify/shopify/pull/106912

Since this is not affecting us anymore I don't think it makes sense for me to fix this _right now_.

That being said, I still think it's worth pursuing. If ok with you, I'll leave this PR open and get back to it at a future point in time.

**Comment by wvanbergen** [comment]
Sure!

**Comment by anthonyn60** [comment]
I'm in favour of this behaviour change. To me, the `store_unqualified` flag implies storing disqualifications specifically. Right now it's being used to handle both assignments AND disqualifications, and in this case, a merchant may disqualify after they've already been qualified.

**Comment by anthonyn60** [comment]
I've modified existing tests and have modified behaviour slightly to make it closer to the original behaviour, i.e. `previous_assignment` is loaded into the `assignment` variable in the `assign` method and `experiment.rb`'s `store_assignment` is always called.

**Comment by eljojo** [comment]
cannot approve my own PR, but the changes made by @anthonyn60 here make sense to me 👍 

:shipit:

**Pull request merged**
